[package]
name = "app"
version = "0.1.0"
description = "ğŸ¤±ğŸ» Turn any webpage into a desktop app with Rust."
authors = ["Tw93"]
license = "MIT"
repository = "https://github.com/tw93/Pake"
default-run = "app"
edition = "2021"
rust-version = "1.63.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.2.1", features = [] }

[dependencies]
serde_json = "1.0.89"
serde = { version = "1.0.150", features = ["derive"] }
tauri = { version = "1.2.4", features = ["api-all", "system-tray"] }
download_rs = { version = "0.2.0", features = ["sync_download"] }
tauri-plugin-window-state = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "dev" }

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = ["custom-protocol"]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = ["tauri/custom-protocol"]


[profile.release]
opt-level = "z" # æˆ–è€… "s"ï¼Œä»¥ä¼˜åŒ–å¤§å°
lto = true
