[package]
name = "app"
version = "0.1.0"
description = "Pake 打包工具"
authors = ["Tw93"]
license = ""
repository = ""
default-run = "app"
edition = "2021"
rust-version = "1.61.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.2.1", features = [] }

[dependencies]
serde_json = "1.0.88"
serde = { version = "1.0.147", features = ["derive"] }
tauri = { version = "1.2.1", features = [] }
image = "0.24.5"
tauri-utils = "1.2.1"
webbrowser = "0.8.2"
wry = "0.21.1"

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = ["custom-protocol"]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = ["tauri/custom-protocol"]
# Enable DevTools for debugging.
devtools = []
